/*

 INITIAL_LOAD.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Project\Tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Inital_LoadWidth 20
#define Inital_LoadHeight 18
#define Inital_LoadBank 0

extern unsigned char Inital_Load[];

/* End of INITIAL_LOAD.H */
